export const GET_ALL_NOTICIAS = "GET_ALL_NOTICIAS"
export const GET_NOTICIA_DETAIL = "GET_NOTICIA_DETAIL"
export const FILTER_NOTICIAS = "FILTER_NOTICIAS"
export const CLEAN_NOTICIA_DETAIL = "CLEAN_NOTICIA_DETAIL"
