export  const devs = [
   {
      image: "https://res.cloudinary.com/drpdobxfu/image/upload/v1695407610/developers/hnfqaiqhxziijsdrbw7y.jpg",
      name: "Gastón Jacinto",
      role: "Full Stack Developer",
      ghub: "https://github.com/GastonJacinto",
      linkedin: "https://www.linkedin.com/in/gastonjacinto/",
   },
   {
      image: "https://res.cloudinary.com/drpdobxfu/image/upload/v1695407515/developers/jaij4ckrutefk1dozzmd.jpg",
      name: "Olivia Dallachiesa",
      role: "Full Stack Developer",
      ghub: "https://github.com/OliviaDallachiesa",
      linkedin: "https://www.linkedin.com/in/olivia-dallachiesa/",
   },
   {
      image: "https://res.cloudinary.com/drpdobxfu/image/upload/v1695414647/developers/a13xbcwfhb2va0u3mxry.jpg",
      name: "Aulio Rovero",
      role: "Full Stack Developer",
      ghub: "https://github.com/Auliorp",
      linkedin: "https://www.linkedin.com/in/auliorovero/",
   },
   {
      image: "https://res.cloudinary.com/drpdobxfu/image/upload/v1695414047/developers/jexpz6ezk804bgjjfhic.jpg",
      name: "Mailen Alassia",
      role: "Full Stack Developer",
      ghub: "https://github.com/alassiamailen",
      linkedin: "https://www.linkedin.com/in/mailenalassia/",
   },
   {
      image: "https://res.cloudinary.com/drpdobxfu/image/upload/v1695413651/developers/vm9yqsfa59ofgqvgofuy.png",
      name: "David De Biazi",
      role: "Full Stack Developer",
      ghub: "https://github.com/Dawyid22",
      linkedin: "https://www.linkedin.com/in/davidalejandrodebiazi/",
   },
   {
      image: "https://res.cloudinary.com/drpdobxfu/image/upload/v1695504894/developers/eupgdxnkal7hraxokrta.jpg",
      name: "Juan Manuel Gonzales",
      role: "Full Stack Developer",
      ghub: "https://github.com/Juannmanuel",
      linkedin: "https://www.linkedin.com/in/juan-manuel-/",
   },
   {
      image: "https://res.cloudinary.com/daoavxvau/image/upload/v1695691847/BrunoDev_gkcnto.png",
      name: "Marcos Bruno Barrancos",
      role: "Full Stack Developer",
      ghub: "https://github.com/MBBrunito",
      linkedin: "https://www.linkedin.com/in/mbbrunito/",
   },
   {
      image: "https://res.cloudinary.com/drpdobxfu/image/upload/v1695504894/developers/ahayes0fsmnaoy6i0fpm.jpg",
      name: "Enzo Arjona",
      role: "Full Stack Developer",
      ghub: "https://github.com/MBBrunito",
      linkedin: "https://www.linkedin.com/in/mbbrunito/",
   },
];