//LOGIN ACTION TYPES//
export const LOCAL_LOGIN = 'LOCAL_LOGIN'
export const LOCAL_LOGIN_ERROR = 'LOCAL_LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'
export const HISTORY = 'HISTORY'
export const LOGGIN_IN = 'LOGGIN_IN'

//ERRORS
export const LOGIN_REGISTER_ERRORS = 'LOGIN_REGISTER_ERRORS'

//REGISTER ACTION TYPES//
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_GOOGLE = 'REGISTER_USER_GOOGLE'
export const REGISTER_USER_LOCAL = 'REGISTER_USER_LOCAL'

//GOOGLE LOGIN ACTION TYPES//
export const GOOGLE_LOGIN ="GOOGLE_LOGIN";