//LOGIN ACTION TYPES//
export const IS_LOADING = 'IS_LOADING'
export const LOCAL_LOGIN = 'LOCAL_LOGIN'
export const LOCAL_LOGIN_ERROR = 'LOCAL_LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'
export const HISTORY = 'HISTORY'
export const LOGGIN_IN = 'LOGGIN_IN'

//ERRORS
export const LOGIN_REGISTER_ERRORS = 'LOGIN_REGISTER_ERRORS'
export const ERROR = 'ERROR'
export const CREATE_LOCAL_PROFILE_ERRORS= "CREATE_LOCAL_PROFILE_ERRORS"
//REGISTER ACTION TYPES//
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_GOOGLE = 'REGISTER_USER_GOOGLE'
export const REGISTER_USER_LOCAL = 'REGISTER_USER_LOCAL'

//GOOGLE LOGIN ACTION TYPES//
export const GOOGLE_LOGIN ="GOOGLE_LOGIN";

//CREAR PERFIL ACTION TYPES
export const CREATE_PROFILE_LOCAL ="CREATE_PROFILE_LOCAL";
export const CREATE_PROFILE_GOOGLE ="CREATE_PROFILE_GOOGLE";

//OBTENER USUARIOS ACTIONS
export const GET_USER_BY_ID = "GET_USER_BY_ID"